
"This input is used to loging a user."
input LoginInput {
  email: String!
  password: String!
}

"Payload returned after a user is logged in."
type LoginPayload {
  token: String!
}


extend type Mutation {
  "This mutation is used to login a user. After a user is logged in a token is returned. This token is simple auth token does not has any checks other than simple validation is not good for production."
  loginUser(input: LoginInput!): LoginPayload!
}
