scalar DateTime
scalar JSON

enum DNSStatus {
  PENDING
  VERIFIED
  FAILED
}

enum DeploymentStatus {
  WORKING
  FAILED
  SUCCESS
}

enum StatusState {
  PASIVE
  ACTIVE
}

enum RedirectionOptions {
  TIMED
  NOT_AUTO_REDIRECT
  DIRECT_HTTP_REDIRECT
  CONFIRM_REDIRECT
}

enum PlatformPermission {
  LINK_CREATE
  LINK_UPDATE
  LINK_DELETE
  LINK_READ
  PLATFORM_READ
  PLATFORM_UPDATE
  PLATFORM_DELETE
}

enum OrganizationPermission {
  DOMAIN_CREATE
  DOMAIN_UPDATE
  DOMAIN_DELETE
  DOMAIN_READ
  ORGANIZATION_READ
  ORGANIZATION_UPDATE
  ORGANIZATION_DELETE
  ORGANIZATION_USER_INVITE
  PLATFORM_CREATE
}

enum InvitationStatus {
  PENDING
  ACCEPTED
  REJECTED
}

enum CrawlStatus {
  REQUESTED
  STARTED
  SUCCESS
  FAILED
}

directive @auth on FIELD_DEFINITION 
directive @organizationPermission(permission: OrganizationPermission!) on INPUT_OBJECT | OBJECT
directive @platformPermission(permission: PlatformPermission!) on INPUT_OBJECT
directive @domainURLCheck on INPUT_OBJECT

type Log{
  id: UUID!
  createdAt: DateTime!
  message: String!
}
