package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"
	"time"

	"github.com/RouteHub-Link/routehub-service-graphql/auth"
	database "github.com/RouteHub-Link/routehub-service-graphql/database/models"
	database_types "github.com/RouteHub-Link/routehub-service-graphql/database/types"
	"github.com/RouteHub-Link/routehub-service-graphql/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreatedAt is the resolver for the createdAt field.
func (r *accountPhoneResolver) CreatedAt(ctx context.Context, obj *database_types.AccountPhone) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *accountPhoneResolver) UpdatedAt(ctx context.Context, obj *database_types.AccountPhone) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Platforms is the resolver for the platforms field.
func (r *companyResolver) Platforms(ctx context.Context, obj *database.Company) ([]*model.Platform, error) {
	panic(fmt.Errorf("not implemented: Platforms - platforms"))
}

// Users is the resolver for the users field.
func (r *companyResolver) Users(ctx context.Context, obj *database.Company) ([]*database.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Domains is the resolver for the domains field.
func (r *companyResolver) Domains(ctx context.Context, obj *database.Company) ([]*model.Domain, error) {
	panic(fmt.Errorf("not implemented: Domains - domains"))
}

// Permissions is the resolver for the permissions field.
func (r *companyResolver) Permissions(ctx context.Context, obj *database.Company) ([]*model.Permission, error) {
	panic(fmt.Errorf("not implemented: Permissions - permissions"))
}

// PaymentPlan is the resolver for the paymentPlan field.
func (r *companyResolver) PaymentPlan(ctx context.Context, obj *database.Company) (model.PaymentPlan, error) {
	panic(fmt.Errorf("not implemented: PaymentPlan - paymentPlan"))
}

// Payments is the resolver for the payments field.
func (r *companyResolver) Payments(ctx context.Context, obj *database.Company) ([]*model.Payment, error) {
	panic(fmt.Errorf("not implemented: Payments - payments"))
}

// Companies is the resolver for the companies field.
func (r *industryResolver) Companies(ctx context.Context, obj *database_types.Industry) ([]*database.Company, error) {
	panic(fmt.Errorf("not implemented: Companies - companies"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*database.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	user, err := r.UserService.Login(input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	userSession := new(auth.UserSession)
	userSession.ID = user.ID
	userSession.Name = user.Fullname

	token, err := auth.GenerateToken(userSession.ToClaims())

	if err != nil {
		return nil, err
	}

	return &model.LoginPayload{
		Token: token,
	}, nil
}

// UpdateUserPassword is the resolver for the updateUserPassword field.
func (r *mutationResolver) UpdateUserPassword(ctx context.Context, userID string, input model.UserUpdatePasswordInput) (*database.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUserPassword - updateUserPassword"))
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input model.PasswordResetCreateInput) (*model.PasswordReset, error) {
	panic(fmt.Errorf("not implemented: RequestPasswordReset - requestPasswordReset"))
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.PasswordResetUpdateInput) (*database.User, error) {
	panic(fmt.Errorf("not implemented: ResetPassword - resetPassword"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*database.User, error) {
	userSession := auth.ForContext(ctx)
	if userSession == nil {
		return nil, gqlerror.Errorf("Access Denied")
	}

	return r.UserService.User(userSession.ID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*database.User, error) {
	return r.UserService.Users()
}

// RefreshToken is the resolver for the refreshToken field.
func (r *queryResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (string, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// Companies is the resolver for the companies field.
func (r *userResolver) Companies(ctx context.Context, obj *database.User) ([]*database.Company, error) {
	return r.UserService.UserCompany(obj.ID)
}

// Platforms is the resolver for the platforms field.
func (r *userResolver) Platforms(ctx context.Context, obj *database.User) ([]*model.Platform, error) {
	panic(fmt.Errorf("not implemented: Platforms - platforms"))
}

// Permissions is the resolver for the permissions field.
func (r *userResolver) Permissions(ctx context.Context, obj *database.User) ([]*model.Permission, error) {
	panic(fmt.Errorf("not implemented: Permissions - permissions"))
}

// Payments is the resolver for the payments field.
func (r *userResolver) Payments(ctx context.Context, obj *database.User) ([]*model.Payment, error) {
	panic(fmt.Errorf("not implemented: Payments - payments"))
}

// AccountPhone returns AccountPhoneResolver implementation.
func (r *Resolver) AccountPhone() AccountPhoneResolver { return &accountPhoneResolver{r} }

// Company returns CompanyResolver implementation.
func (r *Resolver) Company() CompanyResolver { return &companyResolver{r} }

// Industry returns IndustryResolver implementation.
func (r *Resolver) Industry() IndustryResolver { return &industryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type accountPhoneResolver struct{ *Resolver }
type companyResolver struct{ *Resolver }
type industryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
