database:
  host: route-hub
  port: 26257
  user: routehub
  password: xxxx
  database: RouteHub
  application_name: RouteHub-GraphQL
  type:
    migrate: true
    seed: true
    provider: embed
graphql:
  port: 8080
  playground: true
  dataloader:
    wait: 1ms
    cache: true
    lrue:
      size: 1000
      expire: 10m