services:
  domain_utils_host: http://localhost:9001

database:
  host: route-hub
  port: 26257
  user: routehub
  password: xxxx
  database: RouteHub
  application_name: RouteHub-GraphQL
  type:
    migrate: true
    seed: true
    provider: embed
  seed:
    admin:
      email: admin@r4l.com
      password: admin
    organization:
      name: RouteHub
      description: RouteHub is a GraphQL API for managing routes
      url: https://www.routehub.link
    domain:
      name: RouteHub Public Shortener
      url: https://s.r4l.cc

redis:
  addr: 0.0.0.0:6379

graphql:
  port: 8081
  playground: true
  dataloader:
    wait: 1ms
    cache: true
    lrue:
      size: 1000
      expire: 10m

casbin:
  model: ./config/authorization/rbac_model.conf
  log_level: DEBUG
  mongodb:
    uri: mongodb://localhost:27017
    database: casbin
    collection: casbin_rule

authorizer:
  client_id: b20008b0-adec-499a-ac91-272d4c92cdcb
  client_secret: xxx
  token_url: http://localhost:8080/oauth/token
  response_mode: form_post
  response_type: code
  scope: openid profile email
  authorizer_url: http://localhost:8080/authorize
  issuer: http://localhost:8080
  callback: /oauth/callback
  

