services:
  domain_utils_host: http://localhost:9001

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: RouteHub
  application_name: RouteHub-GraphQL
  type:
    migrate: true
    seed: true
    provider: postgres
  seed:
    admins:
      - subject: "248978326325721044"
      - subject: "248979334530971655"
    organization:
      name: RouteHub
      description: RouteHub is a GraphQL API for managing routes
      url: https://www.routehub.link
    domain:
      name: RouteHub Public Shortener
      url: https://s.r4l.cc

redis:
  addr: 0.0.0.0:6379

graphql:
  port: 8081
  playground: true
  dataloader:
    wait: 1ms
    cache: true
    lrue:
      size: 1000
      expire: 10m

casbin:
  model: ./config/authorization/rbac_model.conf
  log_level: DEBUG
  mongodb:
    uri: mongodb://localhost:27017
    database: casbin
    collection: casbin_rule

zitadel:
  client_id: 11111111111
  callback: /oauth2/callback
  scope: openid profile email
  authorizer_url: http://localhost:7077/oauth/v2/authorize
  token_url: http://localhost:7077/oauth/v2/token
  issuer: http://localhost:7077
  domain: 'localhost'
  port: 7077
  insecure: true
